### ISSUE TITLE
installing dependencies using yarn results in error.

### ISSUE THREAD

**Issue by swapnil-chaudhari-1811** [Qafeen/Laravue#5]
Hello Mudasir,

installing dependencies using yarn results in error.

![image](https://user-images.githubusercontent.com/26458928/28521620-1e82c738-7092-11e7-8eda-b771e896334c.png)

**Comment by Modelizer** [comment]
As far I see here file system events is incompatible with win32. Might be a problem and please make sure don't add special characters in directory. It could lead to unexpected errors.
